linters:
  '*.{js}':
    - prettier --write
    - eslint --fix
    - jest --bail --findRelatedTests
    - git add
  '*.json':
    - prettier --write
    - git add
  '*.yml':
    - prettier --write
    - git add
