version: '3.4'
services:
  app:
    build:
      context: .
      target: run
    env_file:
      - .env
    entrypoint: ./start.sh
    ports:
      - 8080:8080
    volumes:
      - .:/srv/app
    links:
      - mongodb
  mongodb:
    image: mongo:4.0.9
    ports:
      - 27017:27017
