[env]
env =  "NODE_ENV"
format = ["production", "development", "test"]
default = "development"

[server]
  [server.port]
    env = "PORT"
    default = 8080
  [server.version]
    env = "API_VERSION"
    default = "1.0.0"

[mongo]
  [mongo.version]
    env = "MONGO_VERSION"
    default = '4.0.9'

[googleMap]
  [googleMap.apiKey]
    env = "GOOGLE_MAP_API_KEY"
    format = "String"
    default = false # make value required
